import type { Metadata } from "next";
import { ThemeModeScript } from "flowbite-react";
import { Open_Sans } from "next/font/google";
import "./globals.css";
import FooterComponents from "@/components/footer";

const openSans = Open_Sans({
  variable: "--font-open-sans",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <ThemeModeScript />
      </head>
      <body className={`${openSans.variable} antialiased`}>
        {children}
        <FooterComponents />
      </body>
    </html>
  );
}
